### ISSUE TITLE
Argument lang to constructor is required

### ISSUE THREAD

**Issue by jjatria** [neilb/WebService-Speechmatics#1]
But the documentation says it is optional (since it can be passed on a per-job basis). Which of these is correct?

I am interested in using this module for my own work, so I'd like to help develop this further.

**Comment by neilb** [comment]
Hi José,

sorry it took me so long to respond. You're right, it should be optional as you say, as long as you then specify the language when submitting a job. I've fixed this in the 0.02 release, which is making its way onto CPAN.

More contributions always welcome! :-)

Cheers,
Neil
